### PR TITLE
feat: add some SDK functions and fix SDK versions

### PR DESCRIPTION
**Pull request by chvonrohr**
We were thrilled to see somebody already created a Mixpanel Capacitor Plugin - many thanks.

Some SDK functionalities we need were not implemented, so we added them within this PR.
As well, it would be helpful to define the Mixpanel SDK version as otherwise it takes latest beta. 

We would like to help you maintaining this plugin and think it would be cool to move this plugin to the Capacitor Community Repo: https://github.com/capacitor-community/welcome - partially backed by the official Ionic maintainers. What do you think?

### CODE REVIEW

**Comment by chvonrohr** [comment]
@mileszim @tetsuwanadam
Two weeks later ;) any objections we publish a fork with our changes to `@capacitor-community/mixpanel`?
Would you like to join forces to maintain this?

**Comment by klemensz** [comment]
Would be great if this could be merged, looking forward to have the "ServerURL config to define EU data residency" functionality.

**Comment by mileszim** [comment]
@chvonrohr @klemensz thank you so much for this!! I am so sorry I have been in the middle of a crazy move, I greatly appreciate your patience here.

@chvonrohr I'd be honored to move this to the capacitor-community. What do you need me to do?

@klemensz will do!

**Comment by klemensz** [comment]
Great, thanks!

@chvonrohr How can the serverUrl be set? Should probably be added to the README.

**Comment by chvonrohr** [comment]
@mileszim I think we need to file a proposal - I saw you found the one ;)

@klemensz sorry forgot to commit my Readme.md changes:

```md
  "plugins": {
   "Mixpanel": {
      "iosToken": "ios-xxx",
      "androidToken": "android-yyy"
      // "serverUrl": "https://api-eu.mixpanel.com" // if Data Residency of Project set to EU
    }
  }
```

**Comment by klemensz** [comment]
Thanks. Looks like the serverUrl won't be picked up by the browser platform version though?

**Comment by chvonrohr** [comment]
@klemensz 
problem is, that AFAIK web plugin can't read capacitor.config.json props. 
What you can do is, for the web use the `initialize` method:

```ts
if (!this.platform.is('capacitor')) {
  Mixpanel.initialize({ token: 'your-token-here', debug: false });
}
```

**Comment by chvonrohr** [comment]
@klemensz Problem is, AFAIK the web plugin can't read the `capacitor.config.json`.
I need to check if somehow possible or use the `initialize` method for that too.

**Comment by klemensz** [comment]
It's possible to pass the `api_host` to the `init()` method of [mixpanel-browser](https://www.npmjs.com/package/mixpanel-browser) library. So only the `options` parameter of the `initialize()` method would need to be extended (but keeping in mind that it would only have effect for the browser variant, which might lead to confusion).

**Pull request merged**
